### 本地开发环境配置
spring:
  application:
    name: system-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/iot_system?serverTimezone=Asia/Shanghai
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 121.42.143.130
      port: 8500
      enabled: true
      discovery:
        health-check-path: /system/actuator/health
        prefer-ip-address: true

  ### 调用追踪配置
  zipkin:
    base-url: http://localhost:9410
  sleuth:
    sampler:
      percentage: 1.0

cassandra:
  host: 121.42.143.130
  port: 9042
  keyspace: gateway

